   ###################### Test Pipeline #####################
kind: pipeline
type: docker
name: TEST-Pipeline
trigger:
  branch:
    - release-candidate/*
  event:
    - pull_request
    - push
concurrency:
  limit: 1

steps:

  - name: echo version
    image: docker:19.03.11-git
    commands:
      - echo $VERSION
    environment:
      VERSION: 1.2
    when:
     event:
       - pull_request

---
