- hosts: localhost

  become: true

  pre_tasks:
  - name: update-repos - pacman
    when: ansible_os_family == "Archlinux"
    pacman: 
     update_cache: yes
     upgrade: yes
    changed_when: False

  - name: update-repos - dnf
    when: ansible_os_family == "RedHat"
    dnf: 
     update_cache: yes
     update_only: yes
    changed_when: False

  tasks:

   - debug:
      msg: "Machine {{ ansible_hostname }} is running {{ ansible_os_family }}"
   - include: Archlinux.yml
     when: ansible_os_family == "Archlinux"
   - include: RedHat.yml
     when: ansible_os_family == "RedHat"


