- hosts: localhost

  become: true

  pre_tasks:
  - name: install requirements
    become: yes
    command: ansible-galaxy install -r requirements.yml
    changed_when: False

  - name: update-repos - pacman
    when: ansible_os_family == "Archlinux"
    pacman:
     update_cache: yes
     upgrade: yes
    changed_when: False

  - name: update-repos - dnf
    when: ansible_os_family == "RedHat"
    dnf:
     update_cache: yes
     update_only: yes
    changed_when: False

  - name: update-repos - apt
    when: ansible_os_family == "Debian"
    apt:
     update_cache: yes
     cache_valid_time: 3600
    changed_when: False

  tasks:

   - debug:
      msg: "Machine {{ ansible_hostname }} is running {{ ansible_os_family }}"
   - name: Include Tasks List Arch
     include_tasks: arch.yml
     when: ansible_os_family == "Archlinux"
   - include_tasks: RedHat.yml
     when: ansible_os_family == "RedHat"
   - include_tasks: debian.yml
     when: ansible_os_family == "Debian"
