- hosts: localhost

  become: true

  pre_tasks:

  - name: update-repos
    pacman: 
     update_cache: yes
     upgrade: yes
    changed_when: False
  
  tasks:
   - include: tasks/Enable-Chaotic-AUR.yml
   - include: tasks/Install-packages.yml
   - include: tasks/Uninstall-packages.yml