- hosts: localhost

  become: true

  pre_tasks:

  - name: update-repos
    pacman: 
     update_cache: yes
     upgrade: yes
    changed_when: False
  
  tasks:
   - include: tasks/users.yml
   - include: tasks/Laptop-changes.yml
   - include: tasks/packages.yml
   - include: tasks/Theming.yml
   - include: tasks/Application-Configuration.yml
   - include: tasks/cron.yml