- name: Libinput Gestures
  blockinfile:
    path: /etc/libinput-gestures.conf
    state: present
    backup: yes
    create: yes
    owner: root
    group: root
    mode: 0440
    insertafter: EOF
    validate: 
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
          # show open apps

          gesture swipe up 3	xdotool key ctrl+F9

          # show application dash

          gesture swipe up 4	xdotool key alt+F1

          # show desktops

          gesture swipe down 4     xdotool key ctrl+F8

          # show desktop
          gesture swipe down 3     xdotool key super+d

          # KDE Plasma open/close overview
          gesture pinch in      xdotool key ctrl+F9
          gesture pinch out     xdotool key ctrl+F9

          device all

- name: Nexcloud Configuration
   copy:
    src: files//nextcloud/nextcloud.cfg
    dest: ~/.config/Nextcloud/
    owner: root
    group: root
    mode: 0440
  copy:
    src: files/nextcloud/sync-exclude.lst
    dest: ~/.config/Nextcloud/
    owner: root
    group: root
    mode: 0440
   systemd:
    state: restarted
    name: nextcloud
    daemon_reload: yes
    become: yes 