- name: Insert chaotic-aur into pacman conf
  blockinfile:
    path: /etc/pacman.conf
    state: present
    backup: yes
    insertafter: EOF
    validate: 
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      [chaotic-aur]
      Server = http://lonewolf-builder.duckdns.org/$repo/x86_64
      Server = http://chaotic.bangl.de/$repo/x86_64
      Server = https://repo.kitsuna.net/x86_64

- name: Add Chaotic Key Mozilla
  become: yes
  command: pacman-key --keyserver keys.mozilla.org -r 3056513887B78AEB 

- name: Add Chaotic Key Lsign
  become: yes
  command: pacman-key --lsign-key 3056513887B78AEB

- name: Enable Bluetooth fast connect
  become: yes
  lineinfile: 
   path: /etc//etc/bluetooth/main.conf
   regex: ^FastConnectable*
   line: FastConnectable = true
   state: present
   backup: yes