- name: install docker
  pacman: name=docker state=present
  tags: docker
  become: true

- name: install virtualbox
  pacman: name=virtualbox state=present
  tags: virtualbox
  become: true

- name: install nextcloud-client
  pacman: name=nextcloud-client state=present
  tags: nextcloud-client
  become: true

- name: install gimp
  pacman: name=gimp state=present
  tags: gimp
  become: true

- name: install aws-cli
  pacman: name=aws-cli state=present
  tags: aws-cli
  become: true

- name: install i3-wm 
  pacman: name=i3-wm  state=present
  tags: i3-wm
  become: true

- name: install code
  pacman: name=code state=present
  tags: code
  become: true

- name: install npm
  pacman: name=npm state=present
  tags: npm
  become: true

- name: install timeshift
  pacman: name=timeshift state=present
  tags: timeshift
  become: true

- name: install latte-dock
  pacman: name=latte-dock state=present
  tags: latte-dock
  become: true

- name: install qbittorrent
  pacman: name=qbittorrent state=present
  tags: qbittorrent
  become: true

- name: install python3
  pacman: name=python3 state=present
  tags: python3
  become: true

- name: install python-pip
  pacman: name=python-pip state=present
  tags: python-pip
  become: true

- name: install stacer
  pacman: name=stacer state=present
  tags: stacer
  become: true

- name: install p7zip
  pacman: name=p7zip state=present
  tags: p7zip
  become: true

- name: install filezilla
  pacman: name=filezilla state=present
  tags: filezilla
  become: true

- name: install steam
  pacman: name=steam state=present
  tags: steam
  become: true

- name: install hamsket
  pacman: name=hamsket state=present
  tags: hamsket
  become: true

- name: install snapd
  pacman: name=snapd state=present
  tags: snapd
  become: true

- name: install bind-tools
  pacman: name=bind-tools state=present
  tags: bind-tools
  become: true

- name: install zoom
  pacman: name=zoom state=present
  tags: zoom
  become: true

- name: install nvme-cli
  pacman: name=nvme-cli state=present
  tags: nvme-cli
  become: true

- name: install sqlite
  pacman: name=sqlite state=present
  tags: sqlite
  become: true

- name: install xclip
  pacman: name=xclip state=present
  tags: xclip
  become: true

- name: install gparted
  pacman: name=gparted state=present
  tags: gparted
  become: true


  snap install bw
  snap install spotify