#- name: Insert KDE Config File /home/john/.kde4/share/config
- name: Copy a new "kdeglobals file into place, backing up the original if it differs from the copied version
  copy:
    src: /files/Themeing/kdeglobals
    dest: /home/john/.kde4/share/config/kdeglobals
    owner: john
    group: john
    mode: '3102'
    backup: yes

#- name: install Theme Dark Moe

#- name: Insert Themes For KDE -  /home/john/.kde4/share/apps/color-schemes
