- name: Install package repos - dnf
  dnf:
   name:
        - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm
        - https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        - https://mirror.ghettoforge.org/distributions/gf/el/8/gf/x86_64/gf-release-8-11.gf.el8.noarch.rpm
   state: latest

- name: Enable Bluetooth fast connect
  become: yes
  lineinfile: 
   path: /etc/bluetooth/main.conf
   regex: FastConnectable =
   line: FastConnectable = true
   state: present
   backup: yes

- name: Setup Auto SSH
  become: yes
  blockinfile: 
   path: ~/.bash_profile
   state: present
   insertafter: EOF
   marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
   block: |
    #add ssh agent at boot
    SSH_ENV="$HOME/.ssh/environment"

    function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
    }

    # Source SSH settings, if applicable
      
    if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
      start_agent;
     }
    else
        start_agent;
    fi

#- name: Disable exhci-wakeup

#- name: Pulseaudio - auto switch profile to HDMI  - https://unix.stackexchange.com/questions/462670/set-default-profile-for-pulseaudio