- hosts: localhost
  tasks:
    - name: OS_family details
      debug:
        msg: "System {{ ansible_hostname }} is running the os {{ ansible_os_family }}"

    #- name: All ansible Variables
    #  debug: var=ansible_facts
