- name: Libinput Gestures
  blockinfile:
    path: /etc/libinput-gestures.conf
    state: present
    backup: yes
    create: yes
    owner: root
    group: root
    mode: 0440
    insertafter: EOF
    validate:
    marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
          # show open apps

          gesture swipe up 3	xdotool key ctrl+F9

          # show application dash

          gesture swipe up 4	xdotool key alt+F1

          # show desktops

          gesture swipe down 4     xdotool key ctrl+F8

          # show desktop
          gesture swipe down 3     xdotool key super+d

          # KDE Plasma open/close overview
          gesture pinch in      xdotool key ctrl+F9
          gesture pinch out     xdotool key ctrl+F9

          device all
#need to change these all to be blocks in files as will get logged out everytime ansible is run
- name: Nextcloud Configuration
  copy:
   src:  ../../files/nextcloud/nextcloud.cfg
   dest: /home/john/.config/Nextcloud/
   owner: john
   group: john
   mode: 0644

  copy:
   src: ../../files/nextcloud/sync-exclude.lst
   dest: /home/john/.config/Nextcloud/
   owner: john
   group: john
   mode: 0644
 # Need to work out how to restart nextcloud

- name: Atom install packages
  become: true
  become_user: john
  command: apm install br4ckets-dark atom-beautify
  changed_when: False

- name: Atom create config file
  copy:
   src: ../../files/atom/config.cson
   dest: /home/john/.atom/config.cson
   owner: john
   group: john
   mode: 0644
   backup: yes


- name: add bitwarden environment variables
  blockinfile:
   path: /home/john/.config/Bitwarden/data.json
   state: present
   insertafter: '"installedVersion": "******",'
   marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
   block: |
         '	"environmentUrls": {
         		"base": "https://bitwarden.johnflix.uk",
         		"api": null,
         		"identity": null,
         		"webVault": null,
         		"icons": null,
         		"notifications": null,
         		"events": null,
         		"enterprise": null
         	},'
