- name: Install KDE Desktop
  pacman:
   name:
   - xorg   kde-applications
   - plasma
   - plasma-wayland-session
   - kde-applications
   state: present

- name: enable SDDM
  systemd:
    name: sddm
    state: started
    enabled: yes

- name: enable NetworkManager
  systemd:
    name: NetworkManager
    state: started
    enabled: yes